// Generated by flutterfire configure — do not edit by hand.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNN-4Wm7gVzk_ibEB5APjChk8FkHVuMo',
    appId: '1:985123178050:android:12cbd26fcc3dfe3ff34fdb',
    messagingSenderId: '985123178050',
    projectId: 'gata-couple',
    storageBucket: 'gata-couple.firebasestorage.app',
  );

  // Reuse Android key for web (local-only usage).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNN-4Wm7gVzk_ibEB5APjChk8FkHVuMo',
    appId: '1:985123178050:android:12cbd26fcc3dfe3ff34fdb',
    messagingSenderId: '985123178050',
    projectId: 'gata-couple',
    storageBucket: 'gata-couple.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNN-4Wm7gVzk_ibEB5APjChk8FkHVuMo',
    appId: '1:985123178050:ios:12cbd26fcc3dfe3ff34fdb',
    messagingSenderId: '985123178050',
    projectId: 'gata-couple',
    storageBucket: 'gata-couple.firebasestorage.app',
    iosBundleId: 'com.subrattandon.gatarandonSubrat-05',
  );
}
